# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hendrik Schick - Software Freelancer/Contractor
email: mail@hendrik-schick.me
description: >- # this means to ignore newlines until "baseurl:"
  Ich schreibe über Softwareentwicklung und weitere Themen, die mir über den Weg laufen. 
  Ich biete Softwareentwicklung und Beratung zur Softwareentwicklung als Freelancer an. Schreibe mir gerne eine E-Mail, 
  wenn du mit mir in Kontakt treten möchtest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hendrik-schick.me" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  ky0n

minima:
  skin: dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/ky0n"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/hendrik-schick/"
    - title: BlueSky
      icon: bluesky
      url: "https://bsky.app/profile/hendrik-schick.me"
    - title: meetup
      icon: meetup
      url: "https://www.meetup.com/members/382573529/"

author:
  name: Hendrik Schick
  email: "mail@hendrik-schick.me"

disqus:
  shortname: hendrik-schick

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
remote_theme: "jekyll/minima@1e8a445"


lsi: false
safe: true
source:
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
gems:
  - jekyll-seo-tag
permalink: /blog/:title

include:
  - favicon.ico

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
